baseURL: "https://sajaldoes.netlify.app"
title: Sajal Das
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Sajal Das
  description: "Sajal Das | Portfolio"
  keywords: [Sajal Das, Portfolio]
  # author: Sajal Das
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: False
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon16x16.ico"
    favicon32x32: "/favicon.ico"
    apple_touch_icon: "/favicon.ico"
    safari_pinned_tab: "/favicon.ico"

  label:
    text: "Sajal Das"
    # icon: /SD.png
    # iconHeight: 24

  # profile-mode
  profileMode:
    enabled: ture
    title: "Sajal Das"
    subtitle: "I am an aspiring **researcher** on **Computer Vision, NLP, ML** from Bangladesh. \U0001f1e7\U0001f1e9 <br>
    Enthusiast of *Data Science*, *Artificial Inteligence*, *Machine Learning*."
    imageUrl: "images/dp.png"
    imageWidth: 220
    imageHeight: 220
    imageTitle: "Sajal Das"
    buttons:
     - name: Academic CV
       url: "/Academic_CV_Sajal_Das.pdf"
     - name: Resume
       url: "/Resume_Sajal_Das.pdf"


  socialIcons:
    - name: "email"
      url: "mailto:contact.sajaldas@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sajaldoes"
    - name: "github"
      url: "https://github.com/sajaldoes"
    - name: twitter
      url: "https://twitter.com/sajaldoes"
    - name: "youtube"
      url: "https://www.youtube.com/c/TechMateSajal"

  analytics:
    google:
      SiteVerificationTag: "G-64FBRXNXHS"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  # editPost:
  #   URL: "https://github.com/sajaldoes/Portfolio/tree/master/content/"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: about
      name: About
      url: /about/
      weight: 20
    - identifier: experiences
      name: Experiences
      url: /experiences/
      weight: 30
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 40
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 50
    # - identifier: blog
    #   name: Blogs
    #   url: /blogs/
    #   weight: 50
    # - identifier: search
    #   name: Search
    #   url: /search
    #   weight: 60


pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
